Article: Interview with robjtede
RustMagazine/rustmagazine pull request #84
Opened 2023-04-12 05:23 UTC by Folyd

2023-05-03 12:48 UTC, robjtede commented on content/issue-3/robjtede.md
> +We are thrilled to present our third interview with **Rob** ([@robjtede]), the core maintainer of [actix-web](https://github.com/actix/actix-web) and [deps.rs](https://deps.rs/). In this interview, w
```suggestion
We are thrilled to present our third interview with **Rob** ([@robjtede]), the core maintainer of [Actix Web](https://github.com/actix/actix-web) and [deps.rs](https://deps.rs/). In this interview, we talked about how he became involved with actix-web, what motivated him to take over the project after [@fafhrd91] quit, and his experience of maintaining popular Rust projects.
```

2023-05-03 12:49 UTC, robjtede commented on content/issue-3/robjtede.md
> +# actix-web
Can "Actix Web" always be formatted like this, please, ie. capitalized and no hyphen:

```suggestion
# Actix Web
```

2023-05-03 13:03 UTC, robjtede commented on content/issue-3/robjtede.md
> +> Rob and a Saitama cosplay from One Punch Man, and his avatar also is Saitama.
just a suggestion:

```suggestion
> Rob uses One Punch Man's Saitama as his avatar online. Here he is meeting his hero.
```

2023-05-03 14:32 UTC, robjtede requested changes

2023-05-03 14:32 UTC, robjtede commented on content/issue-3/robjtede.md
> +**How did you become involved with actix-web, and what motivated you to take over the project after [@fafhrd91] quit?**
```suggestion
**How did you become involved with Actix Web, and what motivated you to take over the project after [@fafhrd91] quit?**
```

2023-05-03 14:32 UTC, robjtede commented on content/issue-3/robjtede.md
> +**What is the current status of actix-web, and how does it compare to two years ago? Are there any major changes or updates in the works?**
```suggestion
**What is the current status of Actix Web, and how does it compare to two years ago? Are there any major changes or updates in the works?**
```

2023-05-03 14:32 UTC, robjtede commented on content/issue-3/robjtede.md
> +**Is actix-web still a web framework powered by the actor model? If not, why?**
```suggestion
**Is Actix Web still a web framework powered by the actor model? If not, why?**
```

2023-05-04 14:20 UTC, merged

2023-05-04 15:44 UTC, Folyd commented on content/issue-3/robjtede.md
> +We are thrilled to present our third interview with **Rob** ([@robjtede]), the core maintainer of [Actix Web](https://github.com/actix/actix-web) and [deps.rs](https://deps.rs/). In this interview, w
Good point, thanks.